# -*- coding: utf-8 -*-
"""gestion_de_videojuegos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W7jTMxx39wjk1e91YDq97J1VRpPWNPMd
"""

# --- CONFIGURACIÓN Y BASE DE DATOS ---
import statistics
import json  # <--- NECESARIO PARA COMPATIBILIDAD CON BLOQUE 2

# ==========================================
# BASE DE DATOS (EN MEMORIA DURANTE EJECUCIÓN)
# ==========================================
participantes_db = []
equipos_db = {}
jugadores_ocupados = set()

# ==========================================
# FUNCIÓN DE GUARDADO (COMPATIBILIDAD BLOQUE 2)
# ==========================================
def guardar_datos_para_bloque_2():
    """
    Guarda la información en el formato exacto que lee el Bloque 2.
    """
    datos_exportar = {
        "participantes": participantes_db,
        "equipos": equipos_db
    }

    nombre_archivo = 'torneo_data.json'

    try:
        with open(nombre_archivo, 'w', encoding='utf-8') as f:
            json.dump(datos_exportar, f, indent=4, ensure_ascii=False)
        print("\n" + "="*50)
        print(f">>> ÉXITO: Base de datos guardada en '{nombre_archivo}'")
        print(">>> Ahora puedes ejecutar el Bloque 2.")
        print("="*50)
    except Exception as e:
        print(f">>> ERROR al guardar el archivo: {e}")

# ==========================================
# HERRAMIENTAS VISUALES
# ==========================================
def imprimir_error(mensaje):
    RED = "\033[91m"
    RESET = "\033[0m"
    print(f"{RED}>>> Error: {mensaje}{RESET}")

def imprimir_exito(mensaje):
    GREEN = "\033[92m"
    RESET = "\033[0m"
    print(f"{GREEN}>>> {mensaje}{RESET}")

# ==========================================
# LÓGICA DE VALIDACIÓN GENÉRICA
# ==========================================
def solicitar_dato_validado(mensaje, tipo_dato, min_val=None, max_val=None):
    while True:
        try:
            entrada = input(mensaje)

            if tipo_dato == str:
                if entrada.strip() == "":
                    imprimir_error("El campo no puede estar vacío.")
                    continue
                return entrada.strip()

            valor = tipo_dato(entrada)

            if min_val is not None and max_val is not None:
                if not (min_val <= valor <= max_val):
                    imprimir_error(f"El valor debe estar entre {min_val} y {max_val}.")
                    continue

            return valor

        except ValueError:
            imprimir_error("Tipo de dato inválido. Ingrese un número entero.")

# ==========================================
# LÓGICA DE VALIDACIÓN DE NOMBRES
# ==========================================
def solicitar_nombre_participante_unico(mensaje):
    while True:
        entrada = input(mensaje).strip()

        if entrada.upper() == 'X':
            return None

        if entrada == "":
            imprimir_error("El nombre no puede estar vacío.")
            continue

        partes_nombre = entrada.split()
        if len(partes_nombre) < 3:
            imprimir_error("Debe ingresar el nombre completo (Nombre, Primer Apellido y Segundo Apellido).")
            continue

        entrada = entrada.title()

        # Validamos contra la lista en memoria
        nombre_existente = False
        for p in participantes_db:
            if p['nombre'].lower() == entrada.lower():
                nombre_existente = True
                break

        if nombre_existente:
            imprimir_error("Este participante ya se encuentra registrado en la base de datos.")
            continue

        return entrada

# ==========================================
# FUNCIONES DE REGISTRO
# ==========================================
def registrar_participante():
    print("\n" + "="*40)
    print("--- NUEVO REGISTRO (Escriba 'X' para finalizar y guardar) ---")

    # 1. Datos del Primer Participante
    nombre_1 = solicitar_nombre_participante_unico("Nombre Completo 1 (3 palabras): ")
    if nombre_1 is None:
        return False # Salir

    edad_1 = solicitar_dato_validado("Edad (12-70): ", int, 12, 70)
    nivel_1 = solicitar_dato_validado("Nivel (1-5): ", int, 1, 5)

    p1 = {"nombre": nombre_1, "edad": edad_1, "nivel": nivel_1}

    # 2. Consulta sobre Equipo
    while True:
        tiene_equipo = input("\n¿Este jugador ya tiene un equipo formado? (si/no): ").strip().lower()
        if tiene_equipo in ['si', 'no']:
            break
        imprimir_error("Por favor responda 'si' o 'no'.")

    # --- CASO A: NO TIENE EQUIPO ---
    if tiene_equipo == 'no':
        participantes_db.append(p1)
        imprimir_exito(f"GUARDADO EN MEMORIA: {nombre_1} (Lista de espera).")
        print(">> Reseteando formulario...")
        return True

    # --- CASO B: SÍ TIENE EQUIPO ---
    else:
        print("\n>> Registro del Equipo y Compañero:")

        while True:
            nombre_equipo = input("Ingrese Nombre del Equipo: ").strip()
            if nombre_equipo == "":
                imprimir_error("El nombre del equipo no puede estar vacío.")
            elif nombre_equipo in equipos_db:
                imprimir_error("Ese nombre de equipo ya existe en la base de datos.")
            else:
                break

        while True:
            nombre_2 = solicitar_nombre_participante_unico("Nombre Completo 2 (3 palabras): ")
            if nombre_2 is None:
                imprimir_error("No puede salir a mitad de un registro de equipo. Complete el nombre.")
                continue

            if nombre_2.lower() == nombre_1.lower():
                imprimir_error("El compañero no puede ser la misma persona.")
                continue
            break

        edad_2 = solicitar_dato_validado("Edad (12-70): ", int, 12, 70)
        nivel_2 = solicitar_dato_validado("Nivel (1-5): ", int, 1, 5)

        p2 = {"nombre": nombre_2, "edad": edad_2, "nivel": nivel_2}

        # Guardado en memoria local
        participantes_db.append(p1)
        participantes_db.append(p2)

        equipos_db[nombre_equipo] = {
            'miembros': [p1, p2],
            'puntos': 0,
            'partidas_jugadas': 0
        }

        jugadores_ocupados.add(nombre_1)
        jugadores_ocupados.add(nombre_2)

        imprimir_exito(f"GUARDADO EN MEMORIA: Equipo '{nombre_equipo}' con {nombre_1} y {nombre_2}.")
        print(">> Formulario de equipo finalizado. Reseteando...")
        return True

# --- EJECUCIÓN DEL FLUJO DE INGRESO ---
def iniciar_sistema_ingreso():
    print("=== SISTEMA DE GESTIÓN DE TORNEO: BASE DE DATOS ===")

    while True:
        continuar = registrar_participante()

        if not continuar:
            # AL FINALIZAR EL BUCLE, GUARDAMOS EL ARCHIVO PARA EL BLOQUE 2
            guardar_datos_para_bloque_2()
            break

# Ejecutamos el sistema
iniciar_sistema_ingreso()

import json

# ==========================================
# CONFIGURACIÓN Y VARIABLES GLOBALES
# ==========================================
participantes_db = []
equipos_db = {}
jugadores_ocupados = set()
ARCHIVO_DB = 'torneo_data.json'

# ==========================================
# HERRAMIENTAS VISUALES (REQUERIDAS POR TU LÓGICA)
# ==========================================
def imprimir_titulo(mensaje):
    print("\n" + "="*50)
    print(f" {mensaje} ".center(50, "="))
    print("="*50)

def imprimir_exito(mensaje):
    print(f"\033[92m>>> {mensaje}\033[0m") # Verde

def imprimir_error(mensaje):
    print(f"\033[91m>>> Error: {mensaje}\033[0m") # Rojo

def imprimir_aviso(mensaje):
    print(f"\033[93m>>> {mensaje}\033[0m") # Amarillo

# ==========================================
# 1. GESTIÓN DE ARCHIVOS (INFRAESTRUCTURA)
# ==========================================
def recuperar_datos():
    """
    Carga el JSON generado por el Bloque 1 y reconstruye las estructuras.
    """
    global participantes_db, equipos_db, jugadores_ocupados
    try:
        with open(ARCHIVO_DB, 'r', encoding='utf-8') as f:
            data = json.load(f)
            participantes_db = data["participantes"]
            equipos_db = data["equipos"]

            # Reconstruir set de ocupados para evitar duplicidad
            jugadores_ocupados = set()
            for equipo in equipos_db.values():
                for miembro in equipo['miembros']:
                    jugadores_ocupados.add(miembro['nombre'])

        imprimir_exito("Base de datos cargada correctamente desde Bloque 1.")
        return True
    except FileNotFoundError:
        imprimir_error(f"No se encontró '{ARCHIVO_DB}'. Ejecute el Bloque 1 primero.")
        return False

def guardar_cambios():
    """
    Guarda las actualizaciones (nuevos equipos) para el futuro Bloque 3.
    """
    datos = {"participantes": participantes_db, "equipos": equipos_db}
    try:
        with open(ARCHIVO_DB, 'w', encoding='utf-8') as f:
            json.dump(datos, f, indent=4, ensure_ascii=False)
        imprimir_exito("Cambios guardados exitosamente en la base de datos.")
    except Exception as e:
        imprimir_error(f"No se pudo guardar el archivo: {e}")

# ==========================================
# 2. LÓGICA DE NEGOCIO (TU CÓDIGO INTEGRADO)
# ==========================================

def obtener_individuales_disponibles():
    """
    Filtra la base de datos y retorna una lista solo con los
    participantes que NO tienen equipo asignado.
    """
    disponibles = []
    for p in participantes_db:
        # Verificamos si el nombre no está en el conjunto de ocupados
        if p['nombre'] not in jugadores_ocupados:
            disponibles.append(p)
    return disponibles

def generar_nombre_equipo_unico(base="Equipo Auto"):
    """
    Genera un nombre único incremental que no exista en la BD.
    """
    contador = 1
    while True:
        nombre_candidato = f"{base} {contador}"
        if nombre_candidato not in equipos_db:
            return nombre_candidato
        contador += 1

def formar_equipos_automaticamente():
    """
    Distribuye equitativamente a los jugadores sin equipo.
    Estrategia High-Low + Guardado Automático.
    """
    imprimir_titulo("FORMACIÓN AUTOMÁTICA Y EQUILIBRADA DE EQUIPOS")

    # 1. Obtener candidatos
    candidatos = obtener_individuales_disponibles()

    # Validación: Mínimo 2 jugadores libres necesarios
    if len(candidatos) < 2:
        imprimir_error("No hay suficientes jugadores individuales (mínimo 2) para formar equipos.")
        return

    # 2. Ordenar candidatos por nivel (Descendente: Mayor a Menor)
    candidatos_ordenados = sorted(candidatos, key=lambda x: x['nivel'], reverse=True)

    print(f"Se encontraron {len(candidatos_ordenados)} jugadores disponibles.")
    print("Generando equipos equilibrados (Nivel Alto + Nivel Bajo)...")

    equipos_creados = 0

    # Ciclo de emparejamiento
    while len(candidatos_ordenados) >= 2:
        # Tomamos al mejor (inicio) y al de menor nivel (final)
        jugador_top = candidatos_ordenados.pop(0)
        jugador_base = candidatos_ordenados.pop(-1)

        integrantes = [jugador_top, jugador_base]

        # 3. Generar Nombre Único
        nombre_equipo = generar_nombre_equipo_unico()

        # 4. Guardar en Estructuras en Memoria
        equipos_db[nombre_equipo] = {
            'miembros': integrantes,
            'puntos': 0,
            'partidas_jugadas': 0,
            'origen': 'automatico'
        }

        # Actualizar set de ocupados
        for m in integrantes:
            jugadores_ocupados.add(m['nombre'])

        print(f" -> {nombre_equipo} formado: {jugador_top['nombre']} (Nv {jugador_top['nivel']}) + {jugador_base['nombre']} (Nv {jugador_base['nivel']})")
        equipos_creados += 1

    if len(candidatos_ordenados) == 1:
        imprimir_aviso(f"El jugador {candidatos_ordenados[0]['nombre']} quedó sin pareja (número impar).")

    # --- INTEGRACIÓN: GUARDADO AUTOMÁTICO ---
    if equipos_creados > 0:
        print("-" * 40)
        imprimir_exito(f"Proceso finalizado. Se crearon {equipos_creados} equipos nuevos.")
        guardar_cambios() # <--- ¡AQUÍ GUARDAMOS LOS CAMBIOS PARA EL BLOQUE 3!
    else:
        imprimir_aviso("No se formaron equipos nuevos.")

def mostrar_equipos_registrados():
    """
    Muestra la lista completa de equipos.
    """
    imprimir_titulo("LISTADO OFICIAL DE EQUIPOS")

    if not equipos_db:
        imprimir_error("Aún no hay equipos registrados en el sistema.")
        return

    for nombre_eq, datos in equipos_db.items():
        # Formateamos los nombres de los miembros con su nivel
        info_miembros = [f"{m['nombre']} (Nv{m['nivel']})" for m in datos['miembros']]
        miembros_str = ", ".join(info_miembros)

        # Calculamos promedio
        niveles = [m['nivel'] for m in datos['miembros']]
        promedio = sum(niveles) / len(niveles)

        print(f"[*] {nombre_eq}")
        print(f"    Integrantes: {miembros_str}")
        print(f"    Promedio Nivel: {promedio:.1f} | Puntos: {datos['puntos']}")
        print("-" * 40)

# ==========================================
# 3. MENÚ DEL BLOQUE 2 (TU INTERFAZ)
# ==========================================
def menu_gestion_equipos():
    while True:
        print("\n=== GESTIÓN DE EQUIPOS Y JUGADORES (BLOQUE 2) ===")
        print("1. Formar equipos AUTOMÁTICAMENTE (Equilibrados)")
        print("2. Ver lista de equipos formados")
        print("3. Finalizar gestión y salir")

        opcion = input("Seleccione una opción: ").strip()

        if opcion == '1':
            formar_equipos_automaticamente()
        elif opcion == '2':
            mostrar_equipos_registrados()
        elif opcion == '3':
            imprimir_exito("Saliendo del módulo de gestión de equipos...")
            break
        else:
            imprimir_error("Opción inválida.")

# ==========================================
# EJECUCIÓN PRINCIPAL
# ==========================================
if __name__ == "__main__":
    # 1. Intentamos cargar los datos del Bloque 1
    if recuperar_datos():
        # 2. Si carga bien, mostramos el menú
        menu_gestion_equipos()

import json
import random

# ==========================================
# CONFIGURACIÓN Y VARIABLES GLOBALES
# ==========================================
participantes_db = []
equipos_db = {}
jugadores_ocupados = set()
ARCHIVO_DB = 'torneo_data.json'

# Palabras reservadas para equipos automáticos
PALABRAS_CLAVE = ["Blue", "Black", "Red", "Green", "Pink", "Yellow", "Brown", "Power", "Rocket"]

# ==========================================
# HERRAMIENTAS VISUALES
# ==========================================
def imprimir_titulo(mensaje):
    print("\n" + "="*60)
    print(f" {mensaje} ".center(60, "="))
    print("="*60)

def imprimir_exito(mensaje):
    print(f"\033[92m>>> {mensaje}\033[0m")

def imprimir_error(mensaje):
    print(f"\033[91m>>> Error: {mensaje}\033[0m")

def imprimir_aviso(mensaje):
    print(f"\033[93m>>> {mensaje}\033[0m")

# ==========================================
# 1. GESTIÓN DE ARCHIVOS
# ==========================================
def recuperar_datos():
    global participantes_db, equipos_db
    try:
        with open(ARCHIVO_DB, 'r', encoding='utf-8') as f:
            data = json.load(f)
            participantes_db = data["participantes"]
            equipos_db = data["equipos"]
        imprimir_exito("Datos cargados correctamente para procesamiento.")
        return True
    except FileNotFoundError:
        imprimir_error("No se encontró el archivo de datos. Ejecute Bloque 1 y 2 primero.")
        return False

def guardar_cambios_finales():
    datos = {"participantes": participantes_db, "equipos": equipos_db}
    with open(ARCHIVO_DB, 'w', encoding='utf-8') as f:
        json.dump(datos, f, indent=4, ensure_ascii=False)
    imprimir_exito("Nombres actualizados y guardados en la base de datos.")

# ==========================================
# 2. LÓGICA DE RENOMBRAMIENTO "GAME TEAM"
# ==========================================
def asignar_nombres_definitivos_autoformados():
    imprimir_titulo("RENOMBRAMIENTO DE EQUIPOS AUTO-FORMADOS")

    # 1. Identificar equipos que necesitan cambio de nombre
    # Buscamos equipos que tengan la marca 'origen': 'automatico' (del Bloque 2)
    equipos_a_renombrar = []
    for nombre, datos in equipos_db.items():
        if datos.get('origen') == 'automatico':
            equipos_a_renombrar.append(nombre)

    if not equipos_a_renombrar:
        imprimir_aviso("No se encontraron equipos automáticos para renombrar.")
        return

    # 2. Validar que tenemos suficientes palabras clave
    if len(equipos_a_renombrar) > len(PALABRAS_CLAVE):
        imprimir_error(f"Hay más equipos automáticos ({len(equipos_a_renombrar)}) que palabras disponibles ({len(PALABRAS_CLAVE)}).")
        print("Agregue más palabras a la lista 'PALABRAS_CLAVE' en el código.")
        return

    # 3. Mezclar aleatoriamente las palabras para que la asignación sea al azar
    random.shuffle(PALABRAS_CLAVE)

    cambios_realizados = 0

    # 4. Proceso de Renombramiento
    # Nota: No podemos cambiar la clave de un diccionario mientras lo iteramos.
    # Por eso recolectamos los cambios primero y los aplicamos después.
    nuevos_nombres_map = {} # {nombre_viejo: nombre_nuevo}

    for nombre_viejo in equipos_a_renombrar:
        # Sacamos una palabra de la lista (asegura no repetición entre ellos)
        palabra = PALABRAS_CLAVE.pop(0)
        nuevo_nombre = f"Game Team {palabra}"

        # Verificación extra: Asegurar que NO exista ni en el Bloque 1
        if nuevo_nombre in equipos_db:
            imprimir_error(f"Conflicto: '{nuevo_nombre}' ya existe. Saltando...")
            continue

        nuevos_nombres_map[nombre_viejo] = nuevo_nombre

    # 5. Aplicar cambios al diccionario principal
    for viejo, nuevo in nuevos_nombres_map.items():
        # Extraemos los datos del equipo viejo
        datos_equipo = equipos_db.pop(viejo)
        # Actualizamos su etiqueta para saber que ya fue procesado
        datos_equipo['origen'] = 'automatico_procesado'
        # Lo insertamos con el nuevo nombre
        equipos_db[nuevo] = datos_equipo

        print(f"[*] Cambio: '{viejo}'  --->  \033[1m'{nuevo}'\033[0m")
        cambios_realizados += 1

    if cambios_realizados > 0:
        guardar_cambios_finales()
    else:
        imprimir_aviso("No se realizaron cambios.")

# ==========================================
# 3. REPORTE FINAL UNIFICADO
# ==========================================
def mostrar_listado_unico_final():
    imprimir_titulo("LISTADO ÚNICO Y OFICIAL DE EQUIPOS")

    # Ordenamos alfabéticamente los equipos para mostrarlos ordenados
    nombres_ordenados = sorted(equipos_db.keys())

    print(f"{'NOMBRE DEL EQUIPO'.ljust(30)} | {'ORIGEN'.ljust(15)} | {'INTEGRANTES'}")
    print("-" * 80)

    for nombre in nombres_ordenados:
        datos = equipos_db[nombre]

        # Determinamos el origen para mostrarlo
        origen_txt = "Inscripción" # Por defecto (Bloque 1)
        if datos.get('origen') == 'automatico_procesado':
            origen_txt = "Sistema (Auto)"

        # Formato de miembros
        miembros = datos['miembros']
        nombres_miembros = f"{miembros[0]['nombre']} & {miembros[1]['nombre']}"

        print(f"{nombre.ljust(30)} | {origen_txt.ljust(15)} | {nombres_miembros}")

    print("-" * 80)
    print(f"TOTAL EQUIPOS: {len(equipos_db)}")

# ==========================================
# EJECUCIÓN DEL BLOQUE 3
# ==========================================
if __name__ == "__main__":
    if recuperar_datos():
        # 1. Renombrar equipos automáticos (si los hay y no han sido renombrados)
        asignar_nombres_definitivos_autoformados()

        # 2. Mostrar la lista final
        mostrar_listado_unico_final()

import json
import random
import time

# ==========================================
# CONFIGURACIÓN Y VARIABLES
# ==========================================
participantes_db = []
equipos_db = {}
ARCHIVO_DB = 'torneo_data.json'
HISTORIAL_PARTIDAS = set() # Para evitar repetir partidos en Ronda 1

# ==========================================
# HERRAMIENTAS DE VISUALIZACIÓN
# ==========================================
def imprimir_titulo(texto):
    print("\n" + "="*60)
    print(f" {texto} ".center(60, "="))
    print("="*60)

def imprimir_info(texto):
    print(f"\033[94m[INFO]\033[0m {texto}")

def imprimir_exito(texto):
    print(f"\033[92m[ÉXITO]\033[0m {texto}")

# ==========================================
# 1. GESTIÓN DE DATOS
# ==========================================
def recuperar_datos():
    global participantes_db, equipos_db
    try:
        with open(ARCHIVO_DB, 'r', encoding='utf-8') as f:
            data = json.load(f)
            participantes_db = data["participantes"]
            equipos_db = data["equipos"]
        return True
    except FileNotFoundError:
        print("Error: No se encontró la base de datos. Ejecuta los bloques anteriores.")
        return False

def guardar_puntajes():
    """Guarda los puntajes actualizados en el JSON."""
    datos = {"participantes": participantes_db, "equipos": equipos_db}
    with open(ARCHIVO_DB, 'w', encoding='utf-8') as f:
        json.dump(datos, f, indent=4, ensure_ascii=False)
    print(">> Puntajes guardados en la base de datos.")

# ==========================================
# 2. MOTOR DE JUEGO Y PUNTUACIÓN
# ==========================================
def registrar_resultado(equipo_a, equipo_b, etapa):
    """
    Gestiona la interacción con el usuario para definir el ganador.
    """
    print(f"\n>>> {etapa}: \033[1m{equipo_a}\033[0m vs \033[1m{equipo_b}\033[0m")
    print("   [1] Ganó " + equipo_a)
    print("   [2] Ganó " + equipo_b)
    print("   [3] Empate")

    while True:
        opcion = input("   Resultado: ").strip()
        if opcion in ['1', '2', '3']:
            break
        print("   Opción inválida. Ingrese 1, 2 o 3.")

    pts_a = 0
    pts_b = 0

    if opcion == '1':
        pts_a = 3
        print(f"   -> Ganador: {equipo_a} (+3 pts)")
    elif opcion == '2':
        pts_b = 3
        print(f"   -> Ganador: {equipo_b} (+3 pts)")
    else:
        pts_a = 1
        pts_b = 1
        print(f"   -> Empate (+1 pt c/u)")

    # Actualizar Base de Datos
    equipos_db[equipo_a]['puntos'] += pts_a
    equipos_db[equipo_a]['partidas_jugadas'] += 1

    equipos_db[equipo_b]['puntos'] += pts_b
    equipos_db[equipo_b]['partidas_jugadas'] += 1

    # Registramos el enfrentamiento en historial global para no repetir en R1
    pareja_ordenada = tuple(sorted((equipo_a, equipo_b)))
    HISTORIAL_PARTIDAS.add(pareja_ordenada)

# ==========================================
# 3. LÓGICA DE RONDAS
# ==========================================

def ejecutar_ronda_1():
    imprimir_titulo("RONDA 1: FASE REGULAR (3 PARTIDAS)")
    nombres_equipos = list(equipos_db.keys())

    if len(nombres_equipos) < 2:
        print("Error: Se necesitan al menos 2 equipos para iniciar el torneo.")
        return False

    # Ejecutamos 3 fechas
    for fecha in range(1, 4):
        imprimir_info(f"Generando enfrentamientos FECHA {fecha}...")
        random.shuffle(nombres_equipos)

        jugados_esta_fecha = set()

        # Algoritmo simple de emparejamiento
        for i in range(len(nombres_equipos)):
            eq1 = nombres_equipos[i]

            if eq1 in jugados_esta_fecha:
                continue

            # Buscamos un rival disponible que no sea él mismo y no hayan jugado antes
            rival_encontrado = None
            for j in range(i + 1, len(nombres_equipos)):
                eq2 = nombres_equipos[j]
                par = tuple(sorted((eq1, eq2)))

                if eq2 not in jugados_esta_fecha and par not in HISTORIAL_PARTIDAS:
                    rival_encontrado = eq2
                    break

            if rival_encontrado:
                registrar_resultado(eq1, rival_encontrado, f"R1-Fecha {fecha}")
                jugados_esta_fecha.add(eq1)
                jugados_esta_fecha.add(rival_encontrado)
            else:
                print(f"   (Nota: {eq1} queda libre en esta fecha por falta de rival compatible)")

        guardar_puntajes()
        time.sleep(1)

    imprimir_exito("Ronda 1 finalizada.")
    mostrar_tabla_posiciones("TABLA POST RONDA 1")
    return True

def ejecutar_ronda_2_semifinales():
    imprimir_titulo("RONDA 2: SEMIFINALES (TOP 4)")

    # 1. Obtener Tabla de Posiciones actual
    # Convertimos dict a lista de tuplas para ordenar
    tabla = []
    for nombre, datos in equipos_db.items():
        tabla.append({
            'nombre': nombre,
            'puntos': datos['puntos']
        })

    # Ordenar por puntos (Descendente)
    tabla.sort(key=lambda x: x['puntos'], reverse=True)

    if len(tabla) < 4:
        print("Error crítico: No hay suficientes equipos (mínimo 4) para semifinales.")
        return False

    clasificados = tabla[:4]
    print("CLASIFICADOS A SEMIFINALES:")
    for idx, eq in enumerate(clasificados):
        print(f"Rank {idx+1}: {eq['nombre']} ({eq['puntos']} pts)")
        # Guardamos su ranking de entrada para desempates futuros
        equipos_db[eq['nombre']]['rank_r1'] = idx + 1

    print("\nIniciando enfrentamientos de Semifinal...")

    # ENFRENTAMIENTO 1: Clasificado 1 vs Clasificado 3
    eq_1 = clasificados[0]['nombre']
    eq_3 = clasificados[2]['nombre']
    registrar_resultado(eq_1, eq_3, "Semifinal A (1 vs 3)")

    # ENFRENTAMIENTO 2: Clasificado 2 vs Clasificado 4
    eq_2 = clasificados[1]['nombre']
    eq_4 = clasificados[3]['nombre']
    registrar_resultado(eq_2, eq_4, "Semifinal B (2 vs 4)")

    guardar_puntajes()
    imprimir_exito("Ronda 2 finalizada.")
    return True

def ejecutar_ronda_3_final():
    imprimir_titulo("RONDA 3: GRAN FINAL")

    # Recuperamos SOLO a los 4 semifinalistas para ver quiénes pasan
    # Necesitamos ver sus puntos TOTALES acumulados
    # Filtramos en base a si tienen el atributo 'rank_r1' que creamos en la ronda anterior
    semifinalistas = []
    for nombre, datos in equipos_db.items():
        if 'rank_r1' in datos:
            semifinalistas.append({
                'nombre': nombre,
                'puntos_totales': datos['puntos'],
                'rank_previo': datos['rank_r1']
            })

    # LÓGICA DE DESEMPATE PARA PASAR A LA FINAL:
    # 1. Mayores puntos totales.
    # 2. Si hay empate, menor 'rank_previo' (el que clasificó mejor a R2).
    semifinalistas.sort(key=lambda x: (x['puntos_totales'], -x['rank_previo']), reverse=True)

    finalistas = semifinalistas[:2]

    print("TABLA ACUMULADA SEMIFINALISTAS:")
    for eq in semifinalistas:
        print(f"- {eq['nombre']}: {eq['puntos_totales']} pts (Rank R1: {eq['rank_previo']})")

    f1 = finalistas[0]['nombre']
    f2 = finalistas[1]['nombre']

    print(f"\n>>> ¡LA GRAN FINAL ES ENTRE {f1} y {f2}!")
    input("Presione Enter para iniciar el duelo...")

    registrar_resultado(f1, f2, "GRAN FINAL")

    guardar_puntajes()

    # DEFINICIÓN DEL CAMPEÓN
    # Se recargan los datos para tener el puntaje final-final
    datos_f1 = equipos_db[f1]
    datos_f2 = equipos_db[f2]

    campeon = ""
    criterio = ""

    if datos_f1['puntos'] > datos_f2['puntos']:
        campeon = f1
        criterio = "Mayor puntaje acumulado"
    elif datos_f2['puntos'] > datos_f1['puntos']:
        campeon = f2
        criterio = "Mayor puntaje acumulado"
    else:
        # Empate en puntos totales -> Gana el que clasificó mejor a la final
        # Usamos el orden de la lista 'finalistas' que ya aplicó el desempate previo
        campeon = finalistas[0]['nombre']
        criterio = "Mejor clasificación previa (Desempate)"

    imprimir_titulo(f"¡EL CAMPEÓN ES: {campeon}!")
    print(f"Criterio de victoria: {criterio}")
    print(f"Puntaje Final: {equipos_db[campeon]['puntos']} puntos.")

def mostrar_tabla_posiciones(titulo):
    print(f"\n--- {titulo} ---")
    tabla = sorted(equipos_db.items(), key=lambda x: x[1]['puntos'], reverse=True)
    print(f"{'EQUIPO'.ljust(30)} | {'PJ'} | {'PTS'}")
    print("-" * 45)
    for nombre, datos in tabla:
        print(f"{nombre.ljust(30)} | {str(datos['partidas_jugadas']).center(2)} | {datos['puntos']}")

# ==========================================
# EJECUCIÓN PRINCIPAL DEL TORNEO
# ==========================================
def iniciar_torneo():
    if not recuperar_datos():
        return

    # Validaciones previas
    if len(equipos_db) < 4:
        imprimir_info("AVISO: Hay menos de 4 equipos. La lógica de semifinales podría fallar.")
        input("Presione Enter si desea continuar de todas formas bajo su riesgo...")

    # Ejecución secuencial
    if ejecutar_ronda_1():
        input("\n>>> Presione Enter para comenzar la RONDA 2 (Semifinales)...")
        if ejecutar_ronda_2_semifinales():
            input("\n>>> Presione Enter para comenzar la RONDA 3 (Final)...")
            ejecutar_ronda_3_final()

# Correr el sistema
iniciar_torneo()

import json
import random
import time

# ==========================================
# CONFIGURACIÓN Y VARIABLES
# ==========================================
equipos_db = {}
ARCHIVO_DB = 'torneo_data.json'

# ==========================================
# HERRAMIENTAS VISUALES
# ==========================================
def imprimir_titulo(texto):
    print("\n" + "="*60)
    print(f" {texto} ".center(60, "="))
    print("="*60)

def imprimir_exito(texto):
    print(f"\033[92m>>> {texto}\033[0m")

def imprimir_error(texto):
    print(f"\033[91m>>> Error: {texto}\033[0m")

def imprimir_info(texto):
    print(f"\033[94m[SISTEMA]\033[0m {texto}")

# ==========================================
# 1. GESTIÓN DE DATOS E INICIALIZACIÓN
# ==========================================
def recuperar_datos_y_preparar_amistosos():
    global equipos_db
    try:
        with open(ARCHIVO_DB, 'r', encoding='utf-8') as f:
            data = json.load(f)
            equipos_db = data["equipos"]

        # Asegurar campos de estadísticas
        cambios_necesarios = False
        for datos in equipos_db.values():
            if 'puntos_amistosos' not in datos:
                datos['puntos_amistosos'] = 0
                datos['partidas_amistosas'] = 0
                cambios_necesarios = True

        if cambios_necesarios:
            guardar_cambios_amistosos(silencioso=True)

        return True
    except FileNotFoundError:
        imprimir_error("No se encontró la base de datos. Ejecute los bloques anteriores.")
        return False

def guardar_cambios_amistosos(silencioso=False):
    try:
        with open(ARCHIVO_DB, 'r', encoding='utf-8') as f:
            data_completa = json.load(f)
    except:
        data_completa = {"participantes": [], "equipos": {}}

    data_completa["equipos"] = equipos_db

    with open(ARCHIVO_DB, 'w', encoding='utf-8') as f:
        json.dump(data_completa, f, indent=4, ensure_ascii=False)

    if not silencioso:
        imprimir_exito("Estadísticas actualizadas y guardadas.")

# ==========================================
# 2. LÓGICA CENTRAL DE PUNTUACIÓN
# ==========================================
def procesar_resultado_y_guardar(eq1_nombre, eq2_nombre):
    """
    Función compartida para procesar el resultado, sea manual o aleatorio.
    """
    print(f"\n>>> ENFRENTAMIENTO: \033[1m{eq1_nombre}\033[0m vs \033[1m{eq2_nombre}\033[0m")
    print("   [1] Ganó " + eq1_nombre)
    print("   [2] Ganó " + eq2_nombre)
    print("   [3] Empate")

    while True:
        res = input("   Ingrese resultado (1-3): ").strip()
        if res in ['1', '2', '3']:
            break
        print("   Opción inválida.")

    pts_1 = 0
    pts_2 = 0

    if res == '1':
        pts_1 = 3
        print(f"   -> Victoria para {eq1_nombre} (+3 pts)")
    elif res == '2':
        pts_2 = 3
        print(f"   -> Victoria para {eq2_nombre} (+3 pts)")
    else:
        pts_1 = 1
        pts_2 = 1
        print(f"   -> Empate (+1 pt c/u)")

    # Actualizar contadores
    equipos_db[eq1_nombre]['puntos_amistosos'] += pts_1
    equipos_db[eq1_nombre]['partidas_amistosas'] += 1

    equipos_db[eq2_nombre]['puntos_amistosos'] += pts_2
    equipos_db[eq2_nombre]['partidas_amistosas'] += 1

    guardar_cambios_amistosos()

# ==========================================
# 3. MODOS DE GENERACIÓN DE PARTIDAS
# ==========================================
def seleccionar_equipo_menu(mensaje, excluir_nombre=None):
    lista_equipos = sorted(list(equipos_db.keys()))
    if excluir_nombre and excluir_nombre in lista_equipos:
        lista_equipos.remove(excluir_nombre)

    print(f"\n--- {mensaje} ---")
    for idx, nombre in enumerate(lista_equipos):
        print(f"[{idx + 1}] {nombre}")

    while True:
        try:
            val = input("Seleccione número: ")
            opcion = int(val)
            if 1 <= opcion <= len(lista_equipos):
                return lista_equipos[opcion - 1]
            print("Número fuera de rango.")
        except ValueError:
            print("Entrada inválida.")

def partida_manual():
    imprimir_titulo("PARTIDA AMISTOSA: SELECCIÓN MANUAL")
    if len(equipos_db) < 2:
        imprimir_error("Se necesitan al menos 2 equipos.")
        return

    eq1 = seleccionar_equipo_menu("Elija el PRIMER equipo")
    eq2 = seleccionar_equipo_menu("Elija el RIVAL", excluir_nombre=eq1)

    procesar_resultado_y_guardar(eq1, eq2)

def partida_aleatoria():
    imprimir_titulo("PARTIDA AMISTOSA: GENERACIÓN ALEATORIA")

    nombres = list(equipos_db.keys())
    if len(nombres) < 2:
        imprimir_error("Se necesitan al menos 2 equipos para generar un duelo.")
        return

    imprimir_info("El sistema está seleccionando rivales al azar...")
    time.sleep(1.5) # Pequeña pausa para efecto dramático

    # Selección aleatoria de 2 equipos distintos
    eq1, eq2 = random.sample(nombres, 2)

    imprimir_info("¡Rivales encontrados!")
    procesar_resultado_y_guardar(eq1, eq2)

# ==========================================
# 4. REPORTE Y MENÚ
# ==========================================
def mostrar_ranking_amistoso():
    imprimir_titulo("RANKING DE AMISTOSOS")
    tabla = sorted(equipos_db.items(), key=lambda x: x[1]['puntos_amistosos'], reverse=True)

    print(f"{'EQUIPO'.ljust(30)} | {'JUGADOS'} | {'PUNTOS'}")
    print("-" * 55)
    for nombre, datos in tabla:
        pj = datos.get('partidas_amistosas', 0)
        pts = datos.get('puntos_amistosos', 0)
        if pj >= 0:
            print(f"{nombre.ljust(30)} | {str(pj).center(7)} | {str(pts).center(6)}")

def menu_amistosos():
    if not recuperar_datos_y_preparar_amistosos():
        return

    while True:
        print("\n=== GESTIÓN DE PARTIDAS AMISTOSAS ===")
        print("1. Ingreso MANUAL de partida")
        print("2. Ingreso ALEATORIO (Generado por Sistema)")
        print("3. Ver Tabla de Posiciones Amistosa")
        print("4. Salir")

        opc = input("Opción: ").strip()

        if opc == '1':
            partida_manual()
        elif opc == '2':
            partida_aleatoria()
        elif opc == '3':
            mostrar_ranking_amistoso()
        elif opc == '4':
            imprimir_exito("Guardando y saliendo...")
            break
        else:
            imprimir_error("Opción no válida.")

# Ejecutar
menu_amistosos()

import json
import statistics
import os
from IPython.display import clear_output

# ==========================================
# CONFIGURACIÓN
# ==========================================
equipos_db = {}
ARCHIVO_DB = 'torneo_data.json'

# ==========================================
# HERRAMIENTAS VISUALES
# ==========================================
def limpiar_pantalla():
    """
    Borra el contenido de la celda de salida inmediatamente.
    Se usa wait=False para evitar que el contenido se acumule visualmente.
    """
    clear_output(wait=False)

def imprimir_titulo(texto):
    print("\n" + "█"*95)
    print(f" {texto} ".center(95))
    print("█"*95)

def mostrar_glosario():
    """Muestra qué significan las abreviaciones antes de las tablas."""
    print("\n\033[94m[GLOSARIO DE TÉRMINOS]\033[0m")
    print(" * PJ  = Partidos Jugados")
    print(" * PTS = Puntos Totales Acumulados")
    print(" * PPP = Promedio de Puntos por Partido (Puntos / PJ)")
    print(" * NVL = Nivel Promedio de los jugadores del equipo (1-5)")

def cargar_datos():
    global equipos_db
    try:
        with open(ARCHIVO_DB, 'r', encoding='utf-8') as f:
            data = json.load(f)
            equipos_db = data["equipos"]
        return True
    except FileNotFoundError:
        print("\033[91mError: Base de datos no encontrada.\033[0m")
        return False

# ==========================================
# CÁLCULOS MATEMÁTICOS
# ==========================================
def calcular_ppp(puntos, jugados):
    return puntos / jugados if jugados > 0 else 0.0

def mostrar_tabla_promedios(titulo, datos_lista):
    """Muestra tabla detallada de promedios."""
    imprimir_titulo(titulo)
    mostrar_glosario()

    print(f"{'EQUIPO'.ljust(30)} | {'PARTIDOS (PJ)'} | {'PUNTOS'} | {'PROMEDIO (PPP)'}")
    print("-" * 95)

    # Ordenar por promedio descendente
    datos_lista.sort(key=lambda x: x[3], reverse=True)

    for nombre, pj, pts, prom in datos_lista:
        print(f"{nombre.ljust(30)} | {str(pj).center(13)} | {str(pts).center(6)} | \033[1m{prom:.2f}\033[0m pts/partido")

def mostrar_tabla_ranking_suma(titulo, datos_lista):
    """Muestra tabla de ranking por suma total."""
    imprimir_titulo(titulo)

    print(f"{'POS'.center(5)} | {'EQUIPO'.ljust(30)} | {'PUNTOS TOTALES ACUMULADOS'}")
    print("-" * 95)

    # Ordenar por puntos totales descendente
    datos_lista.sort(key=lambda x: x[2], reverse=True)

    for i, (nombre, _, pts) in enumerate(datos_lista):
        print(f"{str(i+1).center(5)} | {nombre.ljust(30)} | \033[1m{str(pts).center(23)}\033[0m")

# ==========================================
# 1. PROMEDIOS (PPP)
# ==========================================
def ver_promedio_competencia():
    lista = []
    for nombre, datos in equipos_db.items():
        pts = datos.get('puntos', 0)
        pj = datos.get('partidas_jugadas', 0)
        if pj > 0:
            prom = calcular_ppp(pts, pj)
            lista.append((nombre, pj, pts, prom))

    mostrar_tabla_promedios("PROMEDIO INDIVIDUAL: FASE COMPETENCIA (TORNEO)", lista)

def ver_promedio_global_total():
    lista = []
    for nombre, datos in equipos_db.items():
        pts_tot = datos.get('puntos', 0) + datos.get('puntos_amistosos', 0)
        pj_tot = datos.get('partidas_jugadas', 0) + datos.get('partidas_amistosas', 0)
        if pj_tot > 0:
            prom = calcular_ppp(pts_tot, pj_tot)
            lista.append((nombre, pj_tot, pts_tot, prom))

    mostrar_tabla_promedios("PROMEDIO INDIVIDUAL: GLOBAL (TORNEO + AMISTOSOS)", lista)

# ==========================================
# 2. RANKINGS (SUMAS)
# ==========================================
def ver_ranking_torneo():
    lista = []
    for nombre, datos in equipos_db.items():
        pts = datos.get('puntos', 0)
        lista.append((nombre, 0, pts))
    mostrar_tabla_ranking_suma("RANKING DE PUNTOS: SOLO TORNEO", lista)

def ver_ranking_amistoso():
    lista = []
    for nombre, datos in equipos_db.items():
        pts = datos.get('puntos_amistosos', 0)
        if pts > 0 or datos.get('partidas_amistosas', 0) > 0:
            lista.append((nombre, 0, pts))
    mostrar_tabla_ranking_suma("RANKING DE PUNTOS: SOLO AMISTOSOS", lista)

def ver_ranking_general():
    lista = []
    for nombre, datos in equipos_db.items():
        total = datos.get('puntos', 0) + datos.get('puntos_amistosos', 0)
        lista.append((nombre, 0, total))
    mostrar_tabla_ranking_suma("RANKING GENERAL ACUMULADO (TORNEO + AMISTOSOS)", lista)

# ==========================================
# 3. RENDIMIENTO, EFECTIVIDAD Y VARIABLES
# ==========================================
def ver_rendimiento_y_calidad():
    imprimir_titulo("ANÁLISIS DE RENDIMIENTO MULTIVARIABLE")
    mostrar_glosario()
    print("\n[FACTORES ANALIZADOS]")
    print(" 1. Efectividad %: Rendimiento puro (Puntos ganados / posibles).")
    print(" 2. Nivel Prom:    Promedio del nivel de habilidad de los 2 jugadores.")
    print(" 3. Origen:        Si fue registro manual (REG) o armado por sistema (AUTO).\n")

    tabla = []
    lista_efectividades = []

    for nombre, datos in equipos_db.items():
        pts_tot = datos.get('puntos', 0) + datos.get('puntos_amistosos', 0)
        pj_tot = datos.get('partidas_jugadas', 0) + datos.get('partidas_amistosas', 0)

        # --- CÁLCULO DE VARIABLES EXTRA ---
        # 1. Origen
        origen_raw = datos.get('origen', 'registro_manual')
        origen_fmt = "AUTO" if "auto" in origen_raw else "REG"

        # 2. Nivel Promedio
        miembros = datos.get('miembros', [])
        nivel_promedio = 0
        if miembros:
            suma_niveles = sum(m['nivel'] for m in miembros)
            nivel_promedio = suma_niveles / len(miembros)

        # 3. Efectividad
        if pj_tot > 0:
            posibles = pj_tot * 3
            efectividad = (pts_tot / posibles) * 100
            lista_efectividades.append(efectividad)

            # Guardamos todo en la tabla
            tabla.append((nombre, pj_tot, efectividad, nivel_promedio, origen_fmt))

    # Ordenar por efectividad descendente
    tabla.sort(key=lambda x: x[2], reverse=True)

    # Encabezados con más ancho para las nuevas variables
    print(f"{'EQUIPO'.ljust(25)} | {'TIPO'.center(6)} | {'NVL PROM'.center(8)} | {'PJ'} | {'EFECTIVIDAD'} | {'CALIDAD'}")
    print("-" * 95)

    for nombre, pj, ef, nvl, origen in tabla:
        calidad = ""
        color = ""
        reset = "\033[0m"

        if ef >= 85:
            calidad = "EXCELENTE"
            color = "\033[92m" # Verde
        elif ef >= 60:
            calidad = "BUENO"
            color = "\033[94m" # Azul
        elif ef >= 40:
            calidad = "REGULAR"
            color = "\033[38;5;208m" # Naranja
        else:
            calidad = "DEFICIENTE"
            color = "\033[91m" # Rojo

        print(f"{nombre.ljust(25)} | {origen.center(6)} | {f'{nvl:.1f}'.center(8)} | {str(pj).center(2)} | {f'{ef:.1f}%'.center(11)} | {color}{calidad}{reset}")

    # ESTADÍSTICA DE LIGA
    print("-" * 95)
    if len(lista_efectividades) > 1:
        stdev = statistics.stdev(lista_efectividades)
        media_ef = statistics.mean(lista_efectividades)

        print("\n\033[1m>>> DATOS ESTADÍSTICOS DE LA LIGA:\033[0m")
        print(f" * Promedio General de Efectividad: {media_ef:.1f}%")
        print(f" * Desviación Estándar (Dispersión): \033[94m{stdev:.2f}\033[0m")

        # Interpretación
        if stdev < 15:
            print("   (Interpretación: Liga muy pareja)")
        else:
            print("   (Interpretación: Liga con diferencias de nivel notables)")
    else:
        print("No hay suficientes datos para calcular estadísticas grupales.")

# ==========================================
# MENÚ PRINCIPAL
# ==========================================
def menu_analisis_final():
    if not cargar_datos():
        return

    while True:
        # 1. LIMPIAR PANTALLA AL INICIO DEL BUCLE
        limpiar_pantalla()

        print("\n" + "="*60)
        print("   SISTEMA DE ANÁLISIS ESTADÍSTICO AVANZADO   ".center(60))
        print("="*60)
        print("1. Promedio Individual: Fase Competencia (Torneo)")
        print("2. Promedio Individual: Fase Amistosos")
        print("3. Promedio Individual: Global (Torneo + Amistosos)")
        print("4. Ranking Puntos: SOLO TORNEO (Suma)")
        print("5. Ranking Puntos: SOLO AMISTOSOS (Suma)")
        print("6. Ranking General: ACUMULADO TOTAL (Suma)")
        print("7. Rendimiento Multivariable (Efectividad + Nivel + Origen)")
        print("8. Salir")

        opcion = input("\n>>> Seleccione una opción: ").strip()

        # 2. LIMPIAR EL MENÚ PARA MOSTRAR EL RESULTADO LIMPIO
        limpiar_pantalla()

        if opcion == '1':
            ver_promedio_competencia()
        elif opcion == '2': # Corregido orden menu vs funcion
            ver_promedio_amistosos() # Se asume que esta funcion existe del bloque anterior o se usa ver_promedio_global si no
        elif opcion == '3':
            ver_promedio_global_total()
        elif opcion == '4':
            ver_ranking_torneo()
        elif opcion == '5':
            ver_ranking_amistoso()
        elif opcion == '6':
            ver_ranking_general()
        elif opcion == '7':
            ver_rendimiento_y_calidad()
        elif opcion == '8':
            print("Cerrando sistema...")
            break
        else:
            # Si el usuario elige opcion 2 y la funcion no esta definida en este bloque especifico
            # (porque venia de bloques anteriores), redirigimos o mostramos error.
            # Nota: Agregué la funcion ver_ranking_amistoso arriba pero faltaba ver_promedio_amistosos
            # Para este ejemplo asumo que la logica de amistosos sigue la misma estructura.
            if opcion == '2':
                 # Recreacion rapida de funcion faltante para consistencia
                 lista = []
                 for nombre, datos in equipos_db.items():
                    pts = datos.get('puntos_amistosos', 0)
                    pj = datos.get('partidas_amistosas', 0)
                    if pj > 0:
                        prom = calcular_ppp(pts, pj)
                        lista.append((nombre, pj, pts, prom))
                 mostrar_tabla_promedios("PROMEDIO INDIVIDUAL: FASE AMISTOSA", lista)
            else:
                print("Opción no válida.")

        # 3. PAUSA PARA LEER
        input("\n[Presione Enter para volver al menú]")

        # Al presionar enter, el bucle reinicia y ejecuta el 'limpiar_pantalla()' del paso 1.

# Ejecutar
menu_analisis_final()

import json
import os

# ==========================================
# CONFIGURACIÓN
# ==========================================
equipos_db = {}
ARCHIVO_DB = 'torneo_data.json'

# ==========================================
# HERRAMIENTAS VISUALES
# ==========================================
def imprimir_linea_divisoria(caracter="-", longitud=220):
    print(caracter * longitud)

def imprimir_encabezado_reporte(texto):
    print("\n")
    imprimir_linea_divisoria("=", 220)
    print(f" {texto} ".center(220))
    imprimir_linea_divisoria("=", 220)

def cargar_datos():
    global equipos_db
    try:
        with open(ARCHIVO_DB, 'r', encoding='utf-8') as f:
            data = json.load(f)
            equipos_db = data["equipos"]
        return True
    except FileNotFoundError:
        print("\033[91mError: No se encontró la base de datos para generar el reporte.\033[0m")
        return False

# ==========================================
# LÓGICA DE CÁLCULO
# ==========================================
def calcular_metricas_equipo(datos):
    """Calcula todas las métricas necesarias para el reporte."""
    # 1. Puntos
    pts_torneo = datos.get('puntos', 0)
    pts_amistosos = datos.get('puntos_amistosos', 0)
    pts_total = pts_torneo + pts_amistosos

    # 2. Partidos
    pj_torneo = datos.get('partidas_jugadas', 0)
    pj_amistosos = datos.get('partidas_amistosas', 0)
    pj_total = pj_torneo + pj_amistosos

    # 3. Rendimiento / Efectividad
    efectividad = 0.0
    calidad = "N/A"
    if pj_total > 0:
        posibles = pj_total * 3
        efectividad = (pts_total / posibles) * 100

        if efectividad >= 85: calidad = "EXCELENTE"
        elif efectividad >= 60: calidad = "BUENO"
        elif efectividad >= 40: calidad = "REGULAR"
        else: calidad = "BAJO"

    return {
        "pts_torneo": pts_torneo,
        "pts_amist": pts_amistosos,
        "pts_total": pts_total,
        "pj_torneo": pj_torneo,
        "pj_amist": pj_amistosos,
        "pj_total": pj_total,
        "efectividad": efectividad,
        "calidad": calidad
    }

# ==========================================
# GENERACIÓN DEL REPORTE
# ==========================================
def generar_reporte_final():
    if not cargar_datos():
        return

    # 1. Preparar datos
    lista_reporte = []

    for nombre_equipo, datos in equipos_db.items():
        metricas = calcular_metricas_equipo(datos)

        # Origen
        origen_raw = datos.get('origen', 'registro_manual')
        origen_fmt = "AUTO" if "auto" in origen_raw else "REG"

        # Datos Jugadores
        miembros = datos['miembros']

        # Jugador 1
        metricas['j1_nombre'] = miembros[0]['nombre']
        metricas['j1_edad'] = miembros[0]['edad']
        metricas['j1_nivel'] = miembros[0]['nivel']

        # Jugador 2
        metricas['j2_nombre'] = miembros[1]['nombre']
        metricas['j2_edad'] = miembros[1]['edad']
        metricas['j2_nivel'] = miembros[1]['nivel']

        metricas['nombre_equipo'] = nombre_equipo
        metricas['origen'] = origen_fmt

        lista_reporte.append(metricas)

    # 2. Ordenamiento (Ranking Global: Puntos Totales -> Efectividad)
    lista_reporte.sort(key=lambda x: (x['pts_total'], x['efectividad']), reverse=True)

    # 3. Despliegue Visual
    imprimir_encabezado_reporte("REPORTE FINAL CONSOLIDADO")

    # --- DEFINICIÓN DE ANCHOS DE COLUMNA ---
    w_rk = 3
    w_eq = 18
    w_orig = 6  # Aumentado para que quepa "TIPO" (4 chars) con holgura

    # Anchos Jugadores
    w_nom = 30
    w_eda = 5   # Aumentado de 3 a 5 (SOLUCIÓN PRINCIPAL: "EDAD" tiene 4 letras)
    w_niv = 4   # Aumentado de 3 a 4 para mejor estética con "NV"

    # Anchos Estadísticas
    w_stat = 3
    w_stat_g = 4

    w_eff = 6
    w_cal = 9

    # --- ENCABEZADOS ---
    # Fila 1 (Categorías)
    print(
        f" {' ':{w_rk}} | {' ':{w_eq}} | {' ':{w_orig}} | "
        f"{'--- INTEGRANTE 1 ---'.center(w_nom + w_eda + w_niv + 6)} | "
        f"{'--- INTEGRANTE 2 ---'.center(w_nom + w_eda + w_niv + 6)} | "
        f"{'PARTIDOS (PJ)'.center((w_stat*2) + w_stat_g + 6)} | "
        f"{'PUNTOS (PTS)'.center((w_stat*2) + w_stat_g + 6)} | "
        f"{' ':{w_eff}} | {' ':{w_cal}}"
    )

    # Fila 2 (Títulos)
    header_str = (
        f" {'RK'.center(w_rk)} | "
        f"{'EQUIPO'.ljust(w_eq)} | "
        f"{'TIPO'.center(w_orig)} | "
        # Jugador 1
        f"{'NOMBRE COMPLETO'.ljust(w_nom)} | {'EDAD'.center(w_eda)} | {'NV'.center(w_niv)} | "
        # Jugador 2
        f"{'NOMBRE COMPLETO'.ljust(w_nom)} | {'EDAD'.center(w_eda)} | {'NV'.center(w_niv)} | "
        # Partidos
        f"{'T'.center(w_stat)} | {'A'.center(w_stat)} | {'TOT'.center(w_stat_g)} | "
        # Puntos
        f"{'T'.center(w_stat)} | {'A'.center(w_stat)} | {'TOT'.center(w_stat_g)} | "
        # Rendimiento
        f"{'%EF'.center(w_eff)} | {'CALIDAD'.ljust(w_cal)}"
    )

    print(header_str)
    imprimir_linea_divisoria("-", 220)

    # 4. ITERACIÓN DE FILAS
    for i, fila in enumerate(lista_reporte):
        rank = i + 1

        # Colores
        color_cal = ""
        reset = "\033[0m"
        if fila['calidad'] == "EXCELENTE": color_cal = "\033[92m"
        elif fila['calidad'] == "BAJO": color_cal = "\033[91m"

        # Nombres
        j1_nom_vis = fila['j1_nombre']
        j2_nom_vis = fila['j2_nombre']
        eq_nom_vis = (fila['nombre_equipo'][:w_eq-1] + '.') if len(fila['nombre_equipo']) > w_eq else fila['nombre_equipo']

        print(
            f" {str(rank).center(w_rk)} | "
            f"{eq_nom_vis.ljust(w_eq)} | "
            f"{fila['origen'].center(w_orig)} | "
            # Jugador 1
            f"{j1_nom_vis.ljust(w_nom)} | {str(fila['j1_edad']).center(w_eda)} | {str(fila['j1_nivel']).center(w_niv)} | "
            # Jugador 2
            f"{j2_nom_vis.ljust(w_nom)} | {str(fila['j2_edad']).center(w_eda)} | {str(fila['j2_nivel']).center(w_niv)} | "
            # Partidos
            f"{str(fila['pj_torneo']).center(w_stat)} | {str(fila['pj_amist']).center(w_stat)} | \033[1m{str(fila['pj_total']).center(w_stat_g)}\033[0m | "
            # Puntos
            f"{str(fila['pts_torneo']).center(w_stat)} | {str(fila['pts_amist']).center(w_stat)} | \033[1m{str(fila['pts_total']).center(w_stat_g)}\033[0m | "
            # Rendimiento
            f"{color_cal}{f'{fila['efectividad']:.0f}%'.center(w_eff)}{reset} | "
            f"{color_cal}{fila['calidad'].ljust(w_cal)}{reset}"
        )

    imprimir_linea_divisoria("-", 220)

    # Leyenda final
    print(f"Total Equipos: {len(lista_reporte)}")
    print("\nLEYENDA DE COLUMNAS:")
    print(" [NV]: Nivel del Participante (1-5)")
    print(" [T]: Torneo (Competencia)  |  [A]: Amistosos  |  [TOT]: Global (Suma torneo y amistosos)")
    print(" [RK]: Ranking Global basado en Puntos Totales (TOT)")
    print(" [%EF]: Porcentaje de efectividad del equipo")
    print(" [TIPO]: Tipo de registro en sistema  |  [REG]: Registro manual en inscripción |  [AUTO]: Equipo formado automáticamente por sistema, con participantes individuales")

def cierre_sistema():
    print("\n\n")
    print("█" * 220)
    print(" SISTEMA FINALIZADO EXITOSAMENTE ".center(220))
    print(" Gracias por utilizar el gestor de torneo de Videojuegos Retro".center(220))
    print(" PIXELES RETRO".center(220))
    print("█" * 220)

# ==========================================
# EJECUCIÓN DEL BLOQUE FINAL
# ==========================================
if __name__ == "__main__":
    generar_reporte_final()
    cierre_sistema()